question_data = [{"type": "boolean", "difficulty": "medium", "category": "Animals",
  "question": "An octopus can fit through any hole larger than its beak.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
  "question": "&quot;Santa Claus&quot; is a variety of melon.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy",
  "category": "Entertainment: Japanese Anime &amp; Manga",
  "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
  "question": "MacOS is based on Linux.", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
  "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
  "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "History",
  "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Geography",
  "question": "Rhode Island is actually located on the US mainland, despite its name.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
  "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
  "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Board Games",
  "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
  "question": "Mitsubishi Motors has had a 30-year partnership with Jackie Chan, whose movies have prominently featured their vehicles.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
  "question": "Eurobeat is primarily an Italian genre of music.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "History",
  "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Sports",
  "question": "Shaquille O&rsquo;Neal has only made one three pointer in his career.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
  "question": "The value of one Calorie is different than the value of one calorie.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
  "question": "There are 86400 seconds in a day.", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "Activision created Battlefield 1.", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "History",
  "question": "Augustus was the cousin of Julius Caesar. ", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
  "question": "King Gizzard &amp; The Lizard Wizard&#039;s album &quot;Nonagon Infinity&quot; can be looped seamlessly.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
  "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
  "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy",
  "category": "Entertainment: Japanese Anime &amp; Manga",
  "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
  "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
  "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
  "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Geography",
  "question": "San Marino is the only country completely surrounded by another country.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
  "question": "Slovakia is a member of European Union-", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "History",
  "question": "The Cold War ended with Joseph Stalin&#039;s death.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
  "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
  "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
  "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
  "question": "Like his character in &quot;Parks and Recreation&quot;, Aziz Ansari was born in South Carolina.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
  "question": "Salt is 100% composed of Sodium.", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
  "question": "Super Mario Bros. was released in 1990.", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Geography",
  "question": "There is a city called Rome in every continent on Earth.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "Doki Doki Literature Club was developed in Japan.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
  "question": "In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
  "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
  "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "In the Monster Hunter Series, G-Rank is the highest possible prestige a Hunter can recieve.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
  "question": "A pencil&#039;s lead is typically made from graphite, not lead",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Animals",
  "question": "The Killer Whale is considered a type of dolphin.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
  "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
  "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
  "correct_answer": "True", "incorrect_answers": ["False"]}]
